# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black flake8 flake8-string-format pylint pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Checkstyle
      run: |
        black --check main.py app
    - name: Lint with flake8
      run: |
        flake8 app main.py --count --exit-zero --statistics
    - name: Lint with pylint
      run: |
        pylint app main.py
#        Skipping for now
#    - name: Unit tests
#      run: |
#        pytest tests
#    - name: Component tests
#      run: |
#        python -m pytest component-tests
